services:

  db:
    restart: "no"
    ports:
      - "5447:5432"

  adminer:
    restart: "no"
    ports:
      - "8080:8080"

  backend_unified_search_army_signals:
    restart: "no"
    ports:
      - "8000:8000"
    build:
      context: ./backend
    # command: sleep infinity  # Infinite loop to keep container alive doing nothing
    command:
      - fastapi
      - run
      - --reload
      - "app/main.py"
  
 

 
