"""owner_id, template id added to the form template and form instance table respectively

Revision ID: 4414723fcb19
Revises: 51a029af9a37
Create Date: 2024-12-17 16:00:53.149066

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4414723fcb19'
down_revision: Union[str, None] = '51a029af9a37'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('form_instance', sa.Column('owner_id', sa.UUID(), nullable=False))
    op.add_column('form_instance', sa.Column('template_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'form_instance', 'app_user', ['owner_id'], ['id'])
    op.create_foreign_key(None, 'form_instance', 'form_template', ['template_id'], ['id'])
    op.add_column('form_template', sa.Column('owner_id', sa.UUID(), nullable=False))
    op.drop_constraint('form_template_created_by_fkey', 'form_template', type_='foreignkey')
    op.create_foreign_key(None, 'form_template', 'app_user', ['owner_id'], ['id'])
    op.drop_column('form_template', 'created_by')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('form_template', sa.Column('created_by', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'form_template', type_='foreignkey')
    op.create_foreign_key('form_template_created_by_fkey', 'form_template', 'app_user', ['created_by'], ['id'])
    op.drop_column('form_template', 'owner_id')
    op.drop_constraint(None, 'form_instance', type_='foreignkey')
    op.drop_constraint(None, 'form_instance', type_='foreignkey')
    op.drop_column('form_instance', 'template_id')
    op.drop_column('form_instance', 'owner_id')
    # ### end Alembic commands ###
