"""user table added

Revision ID: 491ad4937219
Revises: 525b59250f6c
Create Date: 2024-11-14 18:14:38.977107

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '491ad4937219'
down_revision: Union[str, None] = '525b59250f6c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('appuser',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('role_id', sa.UUID(), nullable=True),
    sa.Column('org_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['org_id'], ['organization.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_appuser_email'), 'appuser', ['email'], unique=True)
    op.create_index(op.f('ix_appuser_full_name'), 'appuser', ['full_name'], unique=False)
    op.create_index(op.f('ix_appuser_id'), 'appuser', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_appuser_id'), table_name='appuser')
    op.drop_index(op.f('ix_appuser_full_name'), table_name='appuser')
    op.drop_index(op.f('ix_appuser_email'), table_name='appuser')
    op.drop_table('appuser')
    # ### end Alembic commands ###
