"""indexed_table_column added and indexed_table modified

Revision ID: 5ced12dd5ed9
Revises: 7fe4cc640a0f
Create Date: 2024-11-25 13:32:37.676224

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5ced12dd5ed9'
down_revision: Union[str, None] = '7fe4cc640a0f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('indexed_table_column',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('synonyms', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('unique_values', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('table_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['table_id'], ['indexed_table.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_indexed_table_column_id'), 'indexed_table_column', ['id'], unique=False)
    op.create_index(op.f('ix_indexed_table_column_name'), 'indexed_table_column', ['name'], unique=False)
    op.add_column('indexed_table', sa.Column('synonyms', postgresql.ARRAY(sa.String()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('indexed_table', 'synonyms')
    op.drop_index(op.f('ix_indexed_table_column_name'), table_name='indexed_table_column')
    op.drop_index(op.f('ix_indexed_table_column_id'), table_name='indexed_table_column')
    op.drop_table('indexed_table_column')
    # ### end Alembic commands ###
