"""attributes_to_retrieve and access_to_roles added to indexed_table

Revision ID: 64a5eac9066a
Revises: c6d70653e900
Create Date: 2024-12-05 10:31:18.645820

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '64a5eac9066a'
down_revision: Union[str, None] = 'c6d70653e900'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('indexed_table', sa.Column('attributes_to_retrieve', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('indexed_table', sa.Column('access_to_roles', postgresql.ARRAY(sa.UUID()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('indexed_table', 'access_to_roles')
    op.drop_column('indexed_table', 'attributes_to_retrieve')
    
    # ### end Alembic commands ###
