"""relationship_with_other_index table added

Revision ID: 7c187ce2465e
Revises: 64a5eac9066a
Create Date: 2024-12-27 08:52:19.383538

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7c187ce2465e'
down_revision: Union[str, None] = '64a5eac9066a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('indexed_table', sa.Column('relationship_with_other_index', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('indexed_table', 'relationship_with_other_index')
    # ### end Alembic commands ###
