"""extras column added to from_template

Revision ID: 98e9da310e30
Revises: 4414723fcb19
Create Date: 2024-12-19 08:58:09.479942

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '98e9da310e30'
down_revision: Union[str, None] = '4414723fcb19'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('form_template', sa.Column('extras', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('form_template', 'extras')
    # ### end Alembic commands ###
