"""sample data column added to store the sample data from the table

Revision ID: a8b7d881bb1e
Revises: 5ced12dd5ed9
Create Date: 2024-11-25 17:34:37.727746

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a8b7d881bb1e'
down_revision: Union[str, None] = '5ced12dd5ed9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('indexed_table', sa.Column('sample_data', postgresql.ARRAY(postgresql.JSONB(astext_type=sa.Text())), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('indexed_table', 'sample_data')
    # ### end Alembic commands ###