"""indexed_db and indexed_table tables added

Revision ID: e98578b3f077
Revises: 19c7aa5348bb
Create Date: 2024-11-15 07:04:05.238987

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e98578b3f077'
down_revision: Union[str, None] = '19c7aa5348bb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('indexed_db',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_indexed_db_id'), 'indexed_db', ['id'], unique=False)
    op.create_index(op.f('ix_indexed_db_name'), 'indexed_db', ['name'], unique=False)
    op.create_table('indexed_table',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('db_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['db_id'], ['indexed_db.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_indexed_table_id'), 'indexed_table', ['id'], unique=False)
    op.create_index(op.f('ix_indexed_table_name'), 'indexed_table', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_indexed_table_name'), table_name='indexed_table')
    op.drop_index(op.f('ix_indexed_table_id'), table_name='indexed_table')
    op.drop_table('indexed_table')
    op.drop_index(op.f('ix_indexed_db_name'), table_name='indexed_db')
    op.drop_index(op.f('ix_indexed_db_id'), table_name='indexed_db')
    op.drop_table('indexed_db')
    # ### end Alembic commands ###
