"""attributes_to_retrieve

Revision ID: fa5b374dbc71
Revises: 651dd3732075
Create Date: 2024-12-05 06:47:20.027077

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fa5b374dbc71'
down_revision: Union[str, None] = '651dd3732075'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('indexed_table', sa.Column('attributes_to_retrieve', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('indexed_table', 'attributes_to_retrieve')
    # ### end Alembic commands ###
